### ISSUE TITLE
Safer remove child

### ISSUE THREAD

**Issue by GianlucaGuarini** [WebReflection/udomdiff#1]
`domdiff` has a simple test before [removing a node from its parent](https://github.com/WebReflection/domdiff/blob/master/esm/utils.js#L373-L378). `udomdiff` doesn't check the existence of the property `parentNode` on a node  before removing it from the DOM.

Is this behavior intentional or is it a bug?

**Comment by WebReflection** [comment]
In no circumstances udomdiff would remove a node that's not live, the recent comments I've put in the code explain it all
