### ISSUE TITLE
implementing liveview by sending diff data as JSON

### ISSUE THREAD

**Issue by iacore** [WebReflection/udomdiff#11]
The function `udomdiff` applies changes directly. Is there a way that I can get the diff (serializable as JSON) and then later apply the diff?

pseudocode demostrating the concept:

```js
diff = get_patch(newnode, oldnode)
apply_patch(oldnode, diff)
```

This will be useful when there are two copies of `oldnode` (DOM) on server and browser respectively.

Then, I can patch uhtml ``render(oldnode, html`...`)`` (run on server) to update the browser DOM. Event handlers is a bit tricky, and can theoretically be diffed as well.

**Comment by iacore** [comment]
As a side note, is there a community for udomdiff, uhtml and libraries alike? I think it could be pretty useful.

**Comment by WebReflection** [comment]
> Is there a way that I can get the diff (serializable as JSON) and then later apply the diff?

nope, that would bloat the library and there's no use case presented so I don't think it will happen *but*, if it does, it won't be part of `udomdiff`, it will eventually be `udomdiff/json` export, or whatever name it should have.

> is there a community for udomdiff, uhtml and libraries alike?

I don't have time to be on a Discord channel but all discussions are open in all related repositories.

**Comment by iacore** [comment]
I thought more about this, and doing liveview like [dioxus/sledgehammer](https://docs.rs/sledgehammer/latest/sledgehammer/channel/struct.MsgChannel.html) is maybe a bad idea. htmx seems to be much easier to use.

**Comment by WebReflection** [comment]
then use whatever project solves your issue 🥳
