### ISSUE TITLE
Optimal way to handle fragments

### ISSUE THREAD

**Issue by luwes** [WebReflection/udomdiff#3]
This is really an awesome piece of code! Congrats!

I'm trying to incorporate it in `sinuous/map`.
I was wondering about a use case when an item is a document fragment. 
I see it works nicely with arrays.

what do you recommend for handling fragments?
convert the list items to arrays first or use something like uwire?

thanks!

**Comment by WebReflection** [comment]
I am using [uwire](https://github.com/WebReflection/uwire#readme) instances, instead of fragments, and it works seamlessly with [uhtml](https://github.com/WebReflection/uhtml#readme) and [lighterhtml](https://github.com/WebReflection/lighterhtml#readme) already 👍

**Comment by WebReflection** [comment]
P.S. _uwire_ provides the _diffable_ callback to pass to _udomdiff_ out of the box:
https://github.com/WebReflection/uwire/blob/master/esm/index.js#L14-L19

```js
export const diffable = (node, operation) => node.nodeType === nodeType ?
  ((1 / operation) < 0 ?
    (operation ? remove(node) : node.lastChild) :
    (operation ? node.valueOf() : node.firstChild)) :
  node
;
```

That will take care of removing fragments or appending those, as long as these are _uwire_ like fragments.
