### ISSUE TITLE
Compare Function

### ISSUE THREAD

**Issue by PeteSolid** [WebReflection/udomdiff#6]
Hi, I really like domdiff and found out about udomdiff recently.
I also saw that udomdiff is more performant and smaller but does not provide a compare function, like domdiff does.

So I replaced lines https://github.com/WebReflection/udomdiff/blob/master/index.js#L59,
https://github.com/WebReflection/udomdiff/blob/master/index.js#L63 and https://github.com/WebReflection/udomdiff/blob/master/index.js#L69 with the compare Function and run into Problems with insertBefore on line 49.

How would it be possible to add it again?

**Comment by WebReflection** [comment]
It's the same API, the get can be used to compare too, right?

Anyway, udomdiff is as fast as domdiff, and it's being created for uhtml.

Any other use case is not interesting, as there are other libraries to do that (like domdiff)
